# Generated by Django 4.1.2 on 2023-06-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_usuarios_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('password2', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
