# Generated by Django 4.1.2 on 2023-06-29 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0008_usuarios2_imagenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios2',
            name='imagenU',
        ),
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenU', models.ImageField(default='Usuario/static/img/perfil.jpg', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuarios2')),
            ],
        ),
    ]
