# Generated by Django 4.1.2 on 2023-06-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0009_remove_usuarios2_imagenu_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagenU',
            field=models.ImageField(upload_to=''),
        ),
    ]
