# Generated by Django 4.1.2 on 2023-06-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0010_alter_perfil_imagenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios2',
            name='password2',
        ),
        migrations.AlterField(
            model_name='usuarios2',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
